### PR TITLE
build!: update action and dependencies to node 20

### PR DESCRIPTION
**Pull request by hugo-vrijswijk**
Node 16 actions will be deprecated soon and are already giving warnings in CI when this action is used.

### CODE REVIEW

**Comment by hugo-vrijswijk** [comment]
A **lot** of tests are failing due to incorrect lint result comparisons. Probably due to a different build since the last time this repo was touched. I've updated a few of them, but I think fixing the CI is outside of scope for this PR. Other PR's also seem to be failing. I'm not familiar enough with the code or most of the tools to want to touch them any more.

Edits are allowed by maintainers, so any fixes to the build can be picked up by someone else (@ocean90 ?) .

**Comment by INRIX-Iurii-Okhmat** [comment]
@ocean90, @hugo-vrijswijk 
Hello, 
I wonder what needs to happen to get this moving? We rely heavily on this action across numerous projects and it's pretty much the only one left not updated to `node20`

**Comment by ocean90** [comment]
> I wonder what needs to happen to get this moving?

We'd need someone who can make the tests passing again. Either in this PR or in a separate one.

**Comment by hugo-vrijswijk** [comment]
My suggestion would be to merge this PR and fix the tests in a separate one. I'm not familiar enough with this repo to do it, but I don't know who would be

**Comment by erikburt** [comment]
This action is likely to break on May 13 - see https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/.

> Node16 has been out of support since [September 2023](https://github.com/nodejs/Release/#end-of-life-releases). As a result we have started the deprecation process of Node16 for GitHub Actions. We plan to migrate all actions to run on Node20 by Spring 2024.
> Following on from our [warning in workflows using Node16](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) we will start enforcing the use of Node20 rather than Node16 on the 13th of May.

**Comment by ocean90** [comment]
> @ocean90 can you prioritize merging this, and the tests can be fixed retroactively.

That's not possible. The tests need to be fixed first so we can ensure that changes in this PR don't introduce any issues.

**Comment by hugo-vrijswijk** [comment]
> > @ocean90 can you prioritize merging this, and the tests can be fixed retroactively.
> 
> That's not possible. The tests need to be fixed first so we can ensure that changes in this PR don't introduce any issues.

The failing build is due to an outdated build environment setup. Any CI job on master will also fail currently. That makes developing very difficult, as I don't know what/if I've broken with my changes. If the master branch is stable, I'd be more than happy to update this PR and get everything green.

Many people are dependent on this action, which as mentioned above will likely break in less than two weeks (May 13). It would be very helpful if this got merged soon, so someone who knows the code can fix the tests. Merging this now (and publishing a release) would at the very least give people a working version after May 13.

It seems this repo is not very actively maintained any more. If there is no one to actively maintain it, it's understandable, but I think a lot of people would appreciate it if the repo could be archived with a clear notice, or transferred to someone who can maintain it.

**Comment by erikburt** [comment]
Although Github extended the deprecation of node16 by a few months, I have removed any of my dependencies on this action.

I unfortunately suggest you do the same.

**Comment by dystopiandev** [comment]
What did you switch to? @erikburt

**Comment by hugo-vrijswijk** [comment]
I was only using stylelint and prettier, so switching was just a two-line script:

```yaml
      - name: Run linters
        run: |
          npx prettier --check .
          npx stylelint --formatter github .
```

**Comment by hugo-vrijswijk** [comment]
I'm closing this PR. It's a shame this repo seems like it's dead, and not a very good sign for an organization that wants to have a good open source image

**Pull request merged**
