### PR TITLE
Output error from GitHub instead of just 403

### PR DESCRIPTION
**Pull request by hermanbanken**
We had some error which we couldn't resolve without this.

Screenshot 2021-12-02 at 10 43 27

### CODE REVIEW

**Comment by hermanbanken** [comment]
New output:
Screenshot 2021-12-02 at 12 42 41

**Comment by ocean90** [comment]
Hello @hermanbanken, thanks for the PR! Happy to get this merged. Are you able to fix the linting issue? Running `npm run format:fix` should do it.

**Comment by ocean90** [comment]
The message has been changed as part of #371.

**Comment by hermanbanken** [comment]
Thanks!

**Pull request closed without merging**
